spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
        tasks: tasks_view_channel

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
user-service:
  host: localhost
  port: 8080

async:
  executor:
    core-pool-size: 2
    max-pool-size: 4
    queue-capacity: 50
    thread-name-prefix: "Achievement-"
    await-termination-seconds: 60

monitoring:
  thread-pool:
    rate: 60000
    thresholds:
      pool-utilization: 80
      queue-utilization: 70