spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      channel:
        achievement: achievement_channel
        follower: follower_channel
      topic:
        post:
          post-created: post_created_topic

server:
  port: 8085

project-service:
  host: localhost
  port: 8082

kafka:
  server: localhost:9092
  topic:
    achievement-accepted-topic: achievement-accepted-topic
  partitions: 1
  replicas: 1

app:
  async:
    kafka:
      core-pool-size: 10
      max-pool-size: 10