spring:
  mvc:
    servlet:
      path: /api/v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        album: album_channel
        achievement: achievement_channel
        follower: follower_channel
        skill: skill_channel
        project: project_channel
        comment: comment_channel

async:
  thread-name-prefix: AsyncThread-
  core-pool-size: 5
  max-pool-size: 10
  queue_capacity: 25

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
