spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      channels:
        achievement: achievement_channel
        follower: follower_channel
        skill: skill_channel

async:
  core-pool-size: 4
  max-pool-size: 10
  queue-capacity: 100
  thread-name-prefix: PostService-Async-


server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
