spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        achievement:
          name: achievement_channel
        follower:
          name: follower_channel
        goalSetChannel:
          name: goal_set_channel

achievements:
  collector:
    title: COLLECTOR

executor:
  core-pool-size: 10
  max-pool-size: 20
  queue_capacity: 1000

retryable:
  max-attempts: 3
  delay: 5000

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
