name: Build project Griffon Stream-7

on:
  pull_request:
    branches:
      - Griffon-master-stream7

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run tests
        run: docker run --rm myapp:latest pytest tests/

      - name: Deploy
        run: docker run --rm myapp:latest ./deploy.sh

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build
        run: ./gradlew build -x test

      - name: Tests
        run: ./gradlew test

