name: Build project Griffon Stream-7

on:
  pull_request:
    branches:
      - Griffon-master-stream7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test