name: Build project Griffon Stream-7

on:
  pull_request:
    branches:
      - Griffon-master-stream7

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.6
        ports:
          5432:5432
      redis:
        image: redis/redis-stack:latest
      ports:
        6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test